# Generated by Django 4.0.3 on 2023-05-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_pendingaccounts_emailverified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaccounts',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lms.registeredgroups'),
        ),
    ]
