# Generated by Django 4.0.3 on 2023-05-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_pendingaccounts_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaccounts',
            name='group',
            field=models.CharField(max_length=100),
        ),
    ]
