# Generated by Django 4.0.3 on 2023-05-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_pendingaccounts_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='code',
            field=models.CharField(default='alo', max_length=10, unique=True),
        ),
    ]
