# Generated by Django 4.0.3 on 2023-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_courses_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
