# Generated by Django 4.0.3 on 2023-05-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_pendingaccounts_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaccounts',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
