# Generated by Django 4.0.3 on 2023-05-17 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_pendingaccounts_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaccounts',
            name='name',
            field=models.CharField(default='noname', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='noname', max_length=200),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
