# Generated by Django 4.0.3 on 2023-05-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_pendingaccounts_name_user_name_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaccounts',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
