# Generated by Django 4.0.3 on 2023-05-18 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_remove_courses_user_posts_cansubmit_posts_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='canSubmit',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='Off', max_length=3),
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000, null=True)),
                ('file', models.FileField(null=True, upload_to='uploads/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
